school_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('teacher/',include('teacher.urls'))
]

student/urls.py
from django.urls import path
from . import views
app_name='student'

urlpatterns = [
    path ('student_home/',views.get_student_home, name="student_home"),
    path('student_login/',views.get_student_login, name="student_login"),
    path('student_masterpage/',views.get_student_masterpage, name="student_masterpage"),
    path('student_profile/',views.get_student_profile, name="student_profile"),
    path('student_password/',views.get_student_password, name="student_password"),
    path('student_details/',views.get_student_details, name="student_details")
]

teacher/urls.py
from django.urls import path
from . import views
app_name='teacher'

urlpatterns = [
    path('teacher_home/',views.get_teacher_home, name="teacher_home")
]

student/models.py
from django.db import models

# Create your models here.

teacher/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render

# Create your views here.
def get_student_home(request):
    return render(request,"student/student_home.html")

def get_student_login(request):
    return render(request,"student/student_login.html")

def get_student_masterpage(request):
    return render(request,"student/student_masterpage.html")

def get_student_profile(request):
    return render(request, "student/student_profile.html")

def get_student_password(request):
    return render(request, "student/student_password.html")

def get_student_details(request):
    return render(request,"student/student_details.html")

teacher/views.py
from django.shortcuts import render

# Create your views here.
def get_teacher_home(request):
    return render(request,"teacher/teacher_home.html")

student/templates/student/student_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Personal details</h1>
</body>
</html>

student/templates/student/student_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Student details</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto dicta praesentium cum iure amet sint ipsam aliquid molestiae nostrum architecto.</p>
</body>
</html>

student/templates/student/student_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        <label for="">User Name</label>
        <input type="text" name="Student_name" id="">
        <label for="">Password</label>
        <input type="password" name="Student_password" id="">
        <button type="submit">Login</button>
    </form>
</body>
</html>

student/templates/student/student_masterpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div style="height: 500px;width: 300px;float: left;border: 1px solid black;">
        <ul>
            <li><a href="{% url 'student:student_profile' %}">Profile</a></li>
            <li><a href="{% url 'student:student_password' %}">Change password</a></li>
            <li><a href="">About us</a></li>
            <li><a href="">Contact us</a></li>
        </ul>
    </div>
    <div style="height: 500px;width: 1100px;float: left;border: 1px solid black;margin-left: 30px;">
        {% block content %}

        {% endblock %}

    </div>
</body>
</html>

student/templates/student/student_password.html
{% extends 'student/student_masterpage.html' %}
{% block content %}
<h1>Change password</h1>
<label for="">Old password</label>
<input type="password" name="" id=""><br><br>
<label for="">New password</label>
<input type="password" name="" id=""><br><br>
<button>Change</button>

{% endblock %}

student/templates/student/student_profile.html
{% extends 'student/student_masterpage.html' %}
{% load static %}
{% block content %}
<h1>My profile</h1>
<img src="{% static 'images/pic1.jpg' %}" alt=""><br>
<label for="">Name</label>
<input type="text" name="" id=""><br><br>
<label for="">Password</label>
<input type="password" name="" id=""><br><br>
<button>Login</button>
        
{% endblock %}

teacher/templates/teacher/teacher_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Teacher details</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, numquam magni sint ad nesciunt incidunt iste quasi deleniti hic consectetur laudantium, ipsum accusamus, ex odit saepe deserunt? Rerum et voluptas quos dolor cupiditate quaerat numquam fuga! Iure alias, modi soluta ut, nihil quasi sit, earum ducimus veniam nostrum debitis doloribus.</p>
    <button><a href="{% url 'student:student_login' %}">Login</a></button>
</body>
</html>